name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push database image
      run: |
        docker build -t myrepo/postgres:13 ./database
        docker push myrepo/postgres:13

    - name: Build and push API image
      run: |
        docker build -t myrepo/api:latest ./api
        docker push myrepo/api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set context to AKS cluster
      run: az aks get-credentials --resource-group aks-resource-group --name aks-cluster

    - name: Deploy database
      run: |
        helm upgrade --install database ./charts/database

    - name: Deploy API
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        helm upgrade --install api ./charts/api --set env.DATABASE_URL=${{ secrets.DATABASE_URL }}
